server:
  port: 8080
  servlet:
    context-path: /homestay

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/homestay"
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "f8caaef6af81c67c1a9221773cb1bbe982f3f983516e272f2d6285281a709089"
  valid-duration: 3600 #in seconds
  refresh-duration: 36000 #in seconds